"""El banco de qualifiers, literal de la matriz.

GENERADO desde `Data_inputIA/MATRIZ_PACS-H_v1.xlsx`, hoja `8 · Qualifiers v2`,
por `scripts/generar_qualifiers.py`. **No se edita a mano.** Son 60 fichas con
once campos cada una: transcribirlas seria 660 oportunidades de cambiar una
palabra, y el enunciado es lo que el BD lee.

Por que vive aca y no se lee del xlsx
-------------------------------------
Vercel no tiene el libro ni pandas. Y un catalogo que se lee de un archivo que
puede no estar es un catalogo que a veces devuelve vacio -- sin fallar.

Que trae cada uno
-----------------
  enunciado             que se supone que le pasa, en palabras
  escala_de_intensidad  que significa cada nivel de 0 a 3
  evidencia_minima      con que se puede acreditar
  municion_PR_GC        con que se le responde
  angulo_que_activa     el angulo de conversacion
"""
from __future__ import annotations

#: qualifier_id -> sus campos, tal como estan en la hoja 8.
CATALOGO: dict[str, dict] = {
    'J-Q01': {
        'familia': 'JTBD',
        'enunciado': 'Depende del financiamiento para cerrar: su libro de negocio es mayormente buyside',
        'nivel_o_tipo': 'F · detector · CANON v1.0 (sin cambio semantico)',
        'categorias_de_senal': 'S2, S3',
        'senales_de_deteccion': 'Campo MMI Buy Side Sold Units/Volume frente a listing side; contenido sobre pre-aprobacion y "te ayudo a calificar"; acuerdos de representacion de comprador mencionados',
        'escala_de_intensidad': '0 = buyside <40% | 1 = 40-54% | 2 = 55-74% | 3 = >=75% o declara publicamente que solo representa compradores',
        'evidencia_minima': 'Dato duro MMI (capa 1) o declaracion publica explicita. Sin uno de los dos: indeterminado, nunca 0',
        'municion_PR_GC': 'Transversal: habilita PR-Q01, PR-Q02, PR-Q03, PR-Q04 (no aporta municion propia)',
        'angulo_que_activa': 'Ninguno propio: es qualifier de encaje (gating). Si J-Q01<=1 ningun angulo de producto hipotecario puede ser primario',
        'ruta_de_copy': 'R-D',
        'confianza_tipica': 'alta',
    },
    'J-Q02': {
        'familia': 'JTBD',
        'enunciado': 'Necesita poder dar respuesta y estatus a sus clientes fuera del horario bancario',
        'nivel_o_tipo': 'F · detector · CANON v1.0',
        'categorias_de_senal': 'S1, S4, S8',
        'senales_de_deteccion': 'Actividad publicada en noches y fines de semana; reviews que elogian o reclaman disponibilidad; promesa de respuesta en su bio; quejas de "silencio del banco"',
        'escala_de_intensidad': '0 = sin senal de horario extendido | 1 = menciona disponibilidad de forma generica | 2 = patron verificable de actividad nocturna/fin de semana o queja de cliente por falta de respuesta | 3 = lo convierte en promesa de marca ("me escribes a la hora que sea")',
        'evidencia_minima': '>=1 evidencia con fecha (post, review o bio); la inferencia por horario de publicacion sola tope 2',
        'municion_PR_GC': 'GC-4, GC-2, GC-5, PR-8, PR-13; portal y SLA de HOMESI',
        'angulo_que_activa': 'A3 Visibilidad: "nunca mas contestas \'dejame averiguar\'"',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'J-Q03': {
        'familia': 'JTBD',
        'enunciado': 'Busca ser percibido como el/la que si resuelve dentro de su comunidad',
        'nivel_o_tipo': 'S · detector · CANON v1.0',
        'categorias_de_senal': 'S1, S3, S8, S10',
        'senales_de_deteccion': 'Testimonios que publica el mismo; lenguaje de promesa ("yo te ayudo aunque te hayan dicho que no"); patrocinio de eventos comunitarios; idioma del contenido y de las reviews',
        'escala_de_intensidad': '0 = sin huella comunitaria | 1 = testimonios esporadicos sin narrativa | 2 = lenguaje de promesa recurrente en su contenido | 3 = su marca personal esta construida sobre resolver lo que otros rechazan',
        'evidencia_minima': '>=2 piezas de contenido propio en 180 dias con ese lenguaje, o >=3 reviews en el idioma de la comunidad',
        'municion_PR_GC': 'Portafolio de nicho completo; PR-97, PR-100, GC-82, GC-105',
        'angulo_que_activa': 'Modulador social: eleva A1 y A11 a primario cuando coexiste con P-Q01 o P-Q17',
        'ruta_de_copy': 'R-A / R-D',
        'confianza_tipica': 'media',
    },
    'J-Q04': {
        'familia': 'JTBD',
        'enunciado': 'Construye audiencia propia como estrategia deliberada de negocio',
        'nivel_o_tipo': 'S · detector · CANON v1.0 (anclaje conservado)',
        'categorias_de_senal': 'S1, S9',
        'senales_de_deteccion': 'Cadencia de publicacion sostenida; administracion de grupo o pagina; eventos o charlas propias; produccion de video con calidad consistente',
        'escala_de_intensidad': '0 = sin huella | 1 = publica de forma esporadica e irregular | 2 = cadencia constante en al menos un canal durante 90 dias | 3 = administra comunidad o grupo propio y organiza eventos',
        'evidencia_minima': 'Conteo verificable de publicaciones con fecha en >=1 canal publico',
        'municion_PR_GC': 'GC-64, GC-65, GC-68, GC-76, GC-78; PR-91 a PR-98 (co-marketing pro-rata)',
        'angulo_que_activa': 'A8 "Co-financiamos tu maquina de contenido, RESPA-legal"',
        'ruta_de_copy': 'R-D',
        'confianza_tipica': 'alta',
    },
    'J-Q05': {
        'familia': 'JTBD',
        'enunciado': 'Sufre el feast-or-famine y busca previsibilidad de ingreso',
        'nivel_o_tipo': 'E · detector · CANON v1.0',
        'categorias_de_senal': 'S2, S8',
        'senales_de_deteccion': 'Estacionalidad marcada en fechas de cierre; menciones de "meses duros"; suspension visible de pauta en temporada baja; contenido sobre ansiedad de pipeline',
        'escala_de_intensidad': '0 = cierres repartidos en el ano | 1 = estacionalidad leve (<50% en dos trimestres) | 2 = >=60% de cierres concentrados en dos trimestres, o menciona meses secos | 3 = verbaliza la angustia de pipeline o el corte de inversion por falta de caja',
        'evidencia_minima': 'Fechas de transaccion de MMI (campo a solicitar) o declaracion publica fechada',
        'municion_PR_GC': 'GC-10, GC-12, GC-70, GC-81; seminarios PR-97',
        'angulo_que_activa': 'A9 "Tu base vuelve a comprarte" como primario cuando P-Q11>=2; si no, modulador de urgencia',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'J-Q06': {
        'familia': 'JTBD',
        'enunciado': 'Recluta o quiere expandir su propio equipo de agentes',
        'nivel_o_tipo': 'F · detector · CANON v1.0',
        'categorias_de_senal': 'S5, S1',
        'senales_de_deteccion': 'Vacantes publicadas; menciones de "mi equipo"; contenido de reclutamiento; numero de agentes visible en el sitio del brokerage',
        'escala_de_intensidad': '0 = opera solo y sin senal | 1 = menciona equipo sin evidencia verificable | 2 = equipo verificable de 2 a 5 agentes, o una vacante publicada | 3 = vacantes activas mas lenguaje explicito de reclutamiento',
        'evidencia_minima': '>=1 vacante fechada o pagina de equipo con nombres; la mencion aislada de "mi equipo" tope 1',
        'municion_PR_GC': 'GC-96, GC-88, GC-72, GC-83; PR-Q07',
        'angulo_que_activa': 'A17 "Ponemos la estructura que hoy tendrias que montar"',
        'ruta_de_copy': 'R-D',
        'confianza_tipica': 'media',
    },
    'J-Q07': {
        'familia': 'JTBD',
        'enunciado': 'Quiere que su operacion funcione sin su presencia: compra estructura, no herramientas',
        'nivel_o_tipo': 'S/F · detector · NUEVO v2',
        'categorias_de_senal': 'S5, S4, S10',
        'senales_de_deteccion': 'Lenguaje empresarial (sistemas, procesos, SOP, KPI, escalar); asistente o roles definidos; licencia de broker o intencion declarada; stack consolidado en un CRM unico',
        'escala_de_intensidad': '0 = agente individual sin lenguaje de sistema | 1 = habla de "organizarse" sin estructura observable | 2 = SOPs, asistente o roles definidos, o discurso explicito de procesos y metricas | 3 = declara intencion de montar firma o branch, o ya delega operacion real',
        'evidencia_minima': '>=2 senales independientes de S5 o S10; la inferencia desde vocabulario solo tope 2',
        'municion_PR_GC': 'GC-87, GC-88 (Respect Processing), GC-16, GC-72, GC-96',
        'angulo_que_activa': 'A17 "Ponemos la estructura que hoy tendrias que montar"',
        'ruta_de_copy': 'R-D / R-A',
        'confianza_tipica': 'media',
    },
    'J-Q08': {
        'familia': 'JTBD',
        'enunciado': 'Tiene que defender sus honorarios bajo el marco NAR y le falta con que sostenerlos',
        'nivel_o_tipo': 'S/E · detector · NUEVO v2',
        'categorias_de_senal': 'S2, S8, S10',
        'senales_de_deteccion': 'Menciones de acuerdos escritos de representacion; contenido defendiendo el valor del agente; quejas sobre peticiones de rebaja de comision; designaciones ABR',
        'escala_de_intensidad': '0 = sin senal | 1 = opera en mercado con presion de comisiones pero no lo menciona | 2 = menciona acuerdos de representacion o negociacion de honorarios | 3 = verbaliza que le piden bajar comision o publica contenido defendiendo su tarifa',
        'evidencia_minima': 'Declaracion propia fechada para nivel 3; para nivel 2 basta evidencia de uso de acuerdos escritos',
        'municion_PR_GC': 'GC-19, GC-24, GC-29, GC-75, GC-42; PR-13, PR-96',
        'angulo_que_activa': 'A16 "Te damos la otra mitad del argumento de tus honorarios"',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'P-Q01': {
        'familia': 'Pain',
        'enunciado': 'Pierde casos de nicho (ITIN, self-employed, EAD, score 580-640) porque su lender los rechaza de entrada',
        'nivel_o_tipo': 'Detector · CANON v1.0 (anclaje literal conservado)',
        'categorias_de_senal': 'S3, S7, S8',
        'senales_de_deteccion': 'Posts tipo "el banco me rechazo al cliente" o "busco lender ITIN"; comentarios de clientes rechazados; alta densidad de perfiles de nicho en su mercado',
        'escala_de_intensidad': '0 = sin senal | 1 = exposicion probable por composicion del mercado | 2 = senal indirecta (cliente o colega lo menciona) | 3 = lo verbaliza publicamente',
        'evidencia_minima': 'Nivel 3 exige post o comentario propio fechado; nivel 1 puede sostenerse solo con densidad censal del zip (S7)',
        'municion_PR_GC': 'Tax ID MAX (640/15%, EEP 580/3.5%), Supreme Dream, Bank Statement, EAD conventional, ITIN; PR-81, PR-82, PR-86',
        'angulo_que_activa': 'A1 "Rescatamos los casos de nicho que hoy pierdes"',
        'ruta_de_copy': 'R-A si intensidad 3; R-B si 2; R-C si 1',
        'confianza_tipica': 'media',
    },
    'P-Q02': {
        'familia': 'Pain',
        'enunciado': 'El ciclo de cierre de su lender no le permite comprometer una fecha y ganarla',
        'nivel_o_tipo': 'Detector · CANON v1.0 REDEFINIDO (se le extraen las vertientes documental y de estatus)',
        'categorias_de_senal': 'S6, S8, S2',
        'senales_de_deteccion': 'Quejas por demoras; extensiones de contrato mencionadas; reviews de clientes sobre retrasos; mercado donde el plazo desempata ofertas',
        'escala_de_intensidad': '0 = sin senal de demora | 1 = opera en mercado donde el plazo desempata pero no lo menciona | 2 = menciona demoras o extensiones sin atribuirlas | 3 = atribuye publicamente la demora a su prestamista o reporta un cierre perdido por calendario',
        'evidencia_minima': 'Para >=2 se exige mencion propia o de cliente con fecha; la inferencia de mercado tope 1',
        'municion_PR_GC': 'PR-12 (suscripcion 24h), PR-14, PR-15, PR-16, PR-19 (eClosing); GC-1, GC-30; SLA HOMESI',
        'angulo_que_activa': 'A2 "Cierras a tiempo, cada vez"',
        'ruta_de_copy': 'R-A / R-B',
        'confianza_tipica': 'media',
    },
    'P-Q03': {
        'familia': 'Pain',
        'enunciado': 'Se le caen contratos en la recta final por causa financiera',
        'nivel_o_tipo': 'Detector · CANON v1.0',
        'categorias_de_senal': 'S2, S8, S6',
        'senales_de_deteccion': 'Menciones de "se nos cayo"; re-listings del mismo inmueble en ventana corta; reviews que narran un cierre frustrado',
        'escala_de_intensidad': '0 = sin senal | 1 = volumen alto que hace probable la exposicion | 2 = un caso mencionado o un re-listing atribuible | 3 = mas de un caso narrado publicamente o queja explicita sobre la suscripcion tardia',
        'evidencia_minima': 'Un re-listing solo no basta para >=2: exige corroboracion de causa financiera',
        'municion_PR_GC': 'PR-41 a PR-50 (TBD underwriting), PR-17, PR-46; PR-21 a PR-30 (cash-backed)',
        'angulo_que_activa': 'A2 "Cierras a tiempo, cada vez" con municion TBD',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'P-Q04': {
        'familia': 'Pain',
        'enunciado': 'Sus ofertas financiadas pierden sistematicamente contra ofertas en efectivo',
        'nivel_o_tipo': 'Detector · CANON v1.0',
        'categorias_de_senal': 'S7, S2, S8',
        'senales_de_deteccion': 'Mercado con inventario bajo y multiples ofertas; quejas de ofertas perdidas; contenido sobre como competir contra cash',
        'escala_de_intensidad': '0 = mercado sin presion de multiples ofertas | 1 = mercado caliente sin mencion propia | 2 = menciona ofertas perdidas | 3 = narra perdidas repetidas o publica contenido sobre el problema',
        'evidencia_minima': 'Nivel 1 admisible solo con dato de mercado (S7); niveles 2 y 3 exigen voz propia o de cliente',
        'municion_PR_GC': 'PR-21 a PR-30 (cash-backed); GC-31 (delayed financing)',
        'angulo_que_activa': 'A4 "Tu oferta compite de igual a igual"',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'P-Q05': {
        'familia': 'Pain',
        'enunciado': 'Las tasaciones bajas le reabren la negociacion o le tumban el contrato',
        'nivel_o_tipo': 'Detector · CANON v1.0',
        'categorias_de_senal': 'S7, S8, S2',
        'senales_de_deteccion': 'Menciones de appraisal gap; quejas sobre el tasador; mercado con apreciacion rapida donde el comparable va por detras del precio',
        'escala_de_intensidad': '0 = sin senal | 1 = mercado con riesgo estructural de brecha | 2 = menciona una tasacion baja | 3 = narra renegociacion o caida por tasacion',
        'evidencia_minima': 'La inferencia por dinamica de mercado tope 1',
        'municion_PR_GC': 'PR-51 a PR-60 (waivers, ROV, desktop, gap coverage); GC-23 (Simple Seconds 85% CLTV), GC-40, GC-101',
        'angulo_que_activa': 'A4 "Tu oferta compite de igual a igual", vertiente colateral',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'P-Q06': {
        'familia': 'Pain',
        'enunciado': 'Sus clientes se enfrian por el pago mensual y el trato se detiene',
        'nivel_o_tipo': 'Detector · CANON v1.0',
        'categorias_de_senal': 'S3, S7, S8',
        'senales_de_deteccion': 'Contenido sobre tasas y asequibilidad; objeciones de pago citadas en sus posts; listados con dias en mercado altos',
        'escala_de_intensidad': '0 = sin senal | 1 = segmento de precio sensible sin mencion propia | 2 = publica contenido sobre el pago mensual o menciona objeciones | 3 = narra clientes que se retiraron por la cuota',
        'evidencia_minima': 'Contenido educativo generico sobre tasas tope 2: no prueba que el dolor sea suyo',
        'municion_PR_GC': 'PR-73 a PR-78 (buydowns 2-1, 1-0, 3-2-1, puntos, buydown con reembolso); GC-27',
        'angulo_que_activa': 'A5 "Convertimos al que hoy no le alcanza"',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'P-Q07': {
        'familia': 'Pain',
        'enunciado': 'Sus compradores no tienen enganche ni efectivo para los costos de cierre',
        'nivel_o_tipo': 'Detector · CANON v1.0',
        'categorias_de_senal': 'S3, S7',
        'senales_de_deteccion': 'Contenido tipo "compra con poco dinero"; mercado con alta densidad FHA; zips elegibles para programas de asistencia',
        'escala_de_intensidad': '0 = sin senal | 1 = mercado o cartera compatible con el perfil | 2 = publica contenido de bajo enganche o de asistencia | 3 = menciona clientes detenidos por falta de enganche',
        'evidencia_minima': 'Densidad FHA del mercado sostiene nivel 1; niveles 2 y 3 exigen contenido propio',
        'municion_PR_GC': 'Supreme Dream (3.5% forgivable); PR-71, PR-72, PR-79, PR-80 (DPA apilable, hasta $10.000 y $7.000 segun fuente)',
        'angulo_que_activa': 'A5 "Convertimos al que hoy no le alcanza", vertiente capital de entrada',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'P-Q08': {
        'familia': 'Pain',
        'enunciado': 'Su cliente esta atado a su casa actual y no puede comprar sin vender primero',
        'nivel_o_tipo': 'Detector · CANON v1.0',
        'categorias_de_senal': 'S2, S7, S3',
        'senales_de_deteccion': 'Contenido sobre "vende primero"; mercado de move-up con propietarios con plusvalia; menciones de contingencia de venta',
        'escala_de_intensidad': '0 = sin senal | 1 = mercado con perfil move-up dominante | 2 = menciona la contingencia de venta como obstaculo | 3 = narra una oferta descartada por contingencia de venta',
        'evidencia_minima': 'Composicion de cartera (ticket medio-alto, repeat buyers) sostiene nivel 1',
        'municion_PR_GC': 'PR-31 a PR-40 (bridge, buy-before-sell, segunda carga, colateral cruzado); GC-25',
        'angulo_que_activa': 'A6 "Tu cliente compra sin vender primero"',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'P-Q09': {
        'familia': 'Pain',
        'enunciado': 'Pierde inversores porque topan limites de DTI o de numero de propiedades',
        'nivel_o_tipo': 'Detector · CANON v1.0',
        'categorias_de_senal': 'S3, S7, S1',
        'senales_de_deteccion': 'Contenido de inversion; menciones de Airbnb o rentas; presencia en foros o meetups de inversionistas; listados multifamiliares',
        'escala_de_intensidad': '0 = sin senal de cartera de inversion | 1 = algun listado de inversion sin discurso propio | 2 = contenido recurrente para inversionistas | 3 = declara que perdio un inversor por calificacion o que busca producto DSCR',
        'evidencia_minima': 'Un listado multifamiliar aislado no supera 1',
        'municion_PR_GC': 'PR-61 a PR-70 (DSCR, LLC, interest-only, foreign national, Seccion 1031, Schedule 1007); GC-36, GC-49, GC-54, GC-59',
        'angulo_que_activa': 'A7 "Tus inversores nunca tocan techo"',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'P-Q10': {
        'familia': 'Pain',
        'enunciado': 'No tiene tiempo ni recursos para sostener produccion de contenido',
        'nivel_o_tipo': 'Detector · CANON v1.0',
        'categorias_de_senal': 'S1, S9, S4',
        'senales_de_deteccion': 'Cadencia irregular; piezas genericas del brokerage sin personalizacion; ausencia de material propio por listado; sin web propia',
        'escala_de_intensidad': '0 = produccion consistente y de calidad propia | 1 = cadencia irregular con piezas propias | 2 = cadencia irregular y material generico o reciclado | 3 = ausencia de material propio pese a listados activos',
        'evidencia_minima': 'Este qualifier se mide por ausencia observable: la ausencia es evidencia valida, pero exige ventana de >=90 dias',
        'municion_PR_GC': 'GC-64 (co-sponsor 50/50), GC-65, GC-76, GC-78; PR-91 a PR-100',
        'angulo_que_activa': 'A8 "Co-financiamos tu maquina de contenido, RESPA-legal"',
        'ruta_de_copy': 'R-D',
        'confianza_tipica': 'media',
    },
    'P-Q11': {
        'familia': 'Pain',
        'enunciado': 'Pierde el contacto despues del cierre: no tiene sistema de retencion ni de referidos',
        'nivel_o_tipo': 'Detector · CANON v1.0',
        'categorias_de_senal': 'S1, S4, S2',
        'senales_de_deteccion': 'Ausencia de contenido de aniversarios o testimonios antiguos; sin CRM aparente; base larga de clientes sin comunicacion visible',
        'escala_de_intensidad': '0 = evidencia de programa de retencion activo | 1 = contacto post-cierre esporadico | 2 = sin evidencia de retencion con >=5 anos de trayectoria | 3 = sin evidencia de retencion con trayectoria larga y base amplia declarada',
        'evidencia_minima': 'La ausencia sostiene hasta 2; el nivel 3 exige ademas evidencia de base grande (S10 trayectoria o S2 volumen acumulado)',
        'municion_PR_GC': 'GC-9, GC-66, GC-81, GC-10; PR-95',
        'angulo_que_activa': 'A9 "Tu base vuelve a comprarte"',
        'ruta_de_copy': 'R-D',
        'confianza_tipica': 'media',
    },
    'P-Q12': {
        'familia': 'Pain',
        'enunciado': 'Los leads sin calificar le queman tiempo porque no puede precalificar en el acto',
        'nivel_o_tipo': 'Detector · CANON v1.0',
        'categorias_de_senal': 'S1, S4, S8',
        'senales_de_deteccion': 'Menciones de curiosos u open houses sin conversion; registro en papel; ausencia de app o formulario de precalificacion',
        'escala_de_intensidad': '0 = flujo de leads calificado por sistema visible | 1 = sin sistema visible de calificacion | 2 = menciona perdida de tiempo con prospectos no calificados | 3 = lo narra como problema recurrente de su operacion',
        'evidencia_minima': 'Ausencia de herramienta sostiene 1; niveles 2 y 3 exigen voz propia',
        'municion_PR_GC': 'GC-8 (app co-marcada), GC-18 (QR open house), GC-84; PR-13, PR-41 (TBD)',
        'angulo_que_activa': 'A10 "Solo hablas con quien si puede comprar"',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'P-Q13': {
        'familia': 'Pain',
        'enunciado': 'Cuando un caso muere, paga un costo reputacional dentro de su comunidad',
        'nivel_o_tipo': 'Detector · CANON v1.0 · DERIVADO',
        'categorias_de_senal': 'S1, S3, S8',
        'senales_de_deteccion': 'Nicho comunitario fuerte con P-Q01 activo; audiencia local concentrada; testimonios en el idioma de la comunidad',
        'escala_de_intensidad': '0 = no aplica (sin nicho comunitario) | 1 = comunidad identificable sin rol visible | 2 = rol comunitario visible con exposicion de nicho | 3 = influenciador comunitario con casos caidos documentados',
        'evidencia_minima': 'No puede superar el minimo entre P-Q01 y J-Q03: es un qualifier derivado y no se observa por si mismo',
        'municion_PR_GC': 'Angulo social; portafolio de nicho completo; PR-97, GC-82',
        'angulo_que_activa': 'Modulador: eleva A1 a primario y aporta el marco emocional del copy',
        'ruta_de_copy': 'R-A',
        'confianza_tipica': 'baja',
    },
    'P-Q14': {
        'familia': 'Pain',
        'enunciado': 'Sus clientes chocan con la barrera de idioma en el proceso hipotecario',
        'nivel_o_tipo': 'Detector · CANON v1.0',
        'categorias_de_senal': 'S3, S1, S8',
        'senales_de_deteccion': 'Contenido mayoritariamente en espanol; reviews de clientes en espanol; quejas de proceso en ingles; materiales bilingues improvisados',
        'escala_de_intensidad': '0 = operacion integramente en ingles | 1 = contenido bilingue ocasional | 2 = mayoria del contenido o de las reviews en espanol | 3 = declara explicitamente que traduce o acompana a sus clientes en el proceso',
        'evidencia_minima': 'Deteccion de idioma sobre >=10 piezas o >=5 reviews',
        'municion_PR_GC': 'LO bilingue de la casa; materiales y proceso en espanol; PR-100 (biblioteca), GC-14',
        'angulo_que_activa': 'A18 "Tu comunidad en su idioma, de punta a punta" (secundario casi siempre; primario solo si P-Q01<=1)',
        'ruta_de_copy': 'R-D',
        'confianza_tipica': 'alta',
    },
    'P-Q15': {
        'familia': 'Pain',
        'enunciado': 'Termina siendo el cobrador de documentos del expediente de su propio cliente',
        'nivel_o_tipo': 'Detector · NUEVO v2 (vertiente documental extraida de P-Q02)',
        'categorias_de_senal': 'S3, S4, S8',
        'senales_de_deteccion': 'Quejas de "me pidieron lo mismo tres veces"; cartera con alta densidad self-employed o 1099; ausencia de POS del lado del lender; menciones de papeleo',
        'escala_de_intensidad': '0 = sin senal | 1 = cartera con perfiles documentalmente pesados sin mencion propia | 2 = menciona el reproceso documental o hay review de cliente que lo menciona | 3 = lo narra como parte de su rol cotidiano',
        'evidencia_minima': 'La composicion de cartera (S3) sostiene 1; niveles 2 y 3 exigen voz propia o de cliente',
        'municion_PR_GC': 'PR-1 (VOIE), PR-3, PR-4, PR-5, PR-6, PR-7, PR-49; GC-3, GC-13, GC-100',
        'angulo_que_activa': 'A3 Visibilidad y descarga documental',
        'ruta_de_copy': 'R-A / R-B',
        'confianza_tipica': 'media',
    },
    'P-Q16': {
        'familia': 'Pain',
        'enunciado': 'No puede responder por el estatus de su propia transaccion sin llamar a alguien',
        'nivel_o_tipo': 'Detector · NUEVO v2 (vertiente de opacidad extraida de P-Q02)',
        'categorias_de_senal': 'S4, S6, S8',
        'senales_de_deteccion': 'CRM propio activo sin integracion visible; relacion mono-lender sin portal; quejas de "silencio del banco"; menciones de responder tarde',
        'escala_de_intensidad': '0 = opera con portal o integracion verificable | 1 = sin portal visible del lado del lender | 2 = menciona depender de llamadas para saber el estatus | 3 = narra haber quedado mal frente al cliente o al agente del vendedor',
        'evidencia_minima': 'Nivel 1 se sostiene por ausencia de portal (S4/S6); niveles 2 y 3 exigen voz propia',
        'municion_PR_GC': 'PR-2 (sincronizacion LOS-CRM), PR-8, PR-10, PR-20; GC-2, GC-5, GC-79',
        'angulo_que_activa': 'A3 "Nunca mas contestas \'dejame averiguar\'"',
        'ruta_de_copy': 'R-A / R-B',
        'confianza_tipica': 'media',
    },
    'P-Q17': {
        'familia': 'Pain',
        'enunciado': 'Atiende compradores militares o veteranos y les estan dejando dinero en la mesa',
        'nivel_o_tipo': 'Detector · NUEVO v2 (familia nueva declarada en las fichas P-083 a P-085)',
        'categorias_de_senal': 'S3, S7, S10',
        'senales_de_deteccion': 'Mercado con base militar o alta poblacion veterana; contenido dirigido a veteranos; designaciones o lenguaje VA; listados cerca de instalaciones',
        'escala_de_intensidad': '0 = sin exposicion al segmento | 1 = mercado con presencia militar sin discurso propio | 2 = contenido o listados dirigidos a veteranos | 3 = declara especializacion VA o narra un caso VA frustrado',
        'evidencia_minima': 'La presencia de base militar en el zip (S7) sostiene 1 y nunca mas',
        'municion_PR_GC': 'PR-83 (DTI VA >60%), PR-84 (ingreso residual), PR-85 (100% sin PMI), PR-82 (sin overlays)',
        'angulo_que_activa': 'A11 "Al veterano que atiendes le estan dejando dinero en la mesa"',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'P-Q18': {
        'familia': 'Pain',
        'enunciado': 'Tiene inventario que no se puede hipotecar por condicion fisica o por el proyecto',
        'nivel_o_tipo': 'Detector · NUEVO v2 (familia nueva declarada en la ficha P-087)',
        'categorias_de_senal': 'S2, S7, S8',
        'senales_de_deteccion': 'Listados con dias en mercado muy altos; propiedades descritas como "as-is" o "fixer"; condominios no warrantable o con litigio en su zona',
        'escala_de_intensidad': '0 = sin senal | 1 = mercado con stock antiguo o condominios problematicos | 2 = tiene listados as-is o menciona propiedades que no se financian | 3 = narra una venta perdida por inhipotecabilidad',
        'evidencia_minima': 'Los dias en mercado solos no superan 1: exigen corroboracion de condicion del inmueble',
        'municion_PR_GC': 'PR-87 (FHA 203k / HomeStyle); GC-32, GC-33, GC-57',
        'angulo_que_activa': 'A12 "Esa casa si se puede financiar"',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'baja',
    },
    'P-Q19': {
        'familia': 'Pain',
        'enunciado': 'Tiene clientes bloqueados por plazos de espera tras un evento de credito que ya se cumplieron',
        'nivel_o_tipo': 'Detector · NUEVO v2 (familia nueva declarada en la ficha P-089)',
        'categorias_de_senal': 'S3, S7, S8',
        'senales_de_deteccion': 'Contenido sobre reconstruccion de credito; mercado con alta incidencia de eventos crediticios recientes; menciones de clientes que "todavia no pueden"',
        'escala_de_intensidad': '0 = sin senal | 1 = cartera compatible sin discurso propio | 2 = publica contenido de recuperacion crediticia | 3 = menciona clientes esperando plazos o consulta por tiempos de espera',
        'evidencia_minima': 'Nivel 1 solo por composicion demografica del mercado',
        'municion_PR_GC': 'PR-89 (plazos federales minimos, Cap. 7 a 2 anos); GC-34, GC-55 (Portfolio Select a 1 ano), GC-60',
        'angulo_que_activa': 'A13 "Ya pasaron los anos de espera y nadie se lo dijo"',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'baja',
    },
    'P-Q20': {
        'familia': 'Pain',
        'enunciado': 'Sus clientes de ingreso alto sin W-2 son rechazados por el ratio y no por su solvencia',
        'nivel_o_tipo': 'Detector · NUEVO v2 (se separa de P-Q01 porque la conversacion y la municion difieren)',
        'categorias_de_senal': 'S3, S7, S2',
        'senales_de_deteccion': 'Ticket promedio alto con cartera de empresarios o profesionales independientes; contenido dirigido a duenos de negocio o jubilados; zips de renta alta',
        'escala_de_intensidad': '0 = sin senal | 1 = ticket alto sin perfil identificable | 2 = cartera o contenido orientado a self-employed de ingreso alto, jubilados o gig de alto volumen | 3 = narra un rechazo de cliente solvente por documentacion de ingreso',
        'evidencia_minima': 'El ticket promedio (dato MMI) sostiene 1; niveles 2 y 3 exigen senal de perfil de cliente',
        'municion_PR_GC': 'PR-81 (bank statement 12/24m); GC-43, GC-44, GC-45, GC-46, GC-51, GC-53, GC-56',
        'angulo_que_activa': 'A14 "Tu cliente de ingreso alto sin W-2 si califica"',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'P-Q21': {
        'familia': 'Pain',
        'enunciado': 'Hace o evita co-marketing sin saber si lo que hace resiste una revision',
        'nivel_o_tipo': 'Detector · NUEVO v2 (familia nueva: riesgo normativo percibido)',
        'categorias_de_senal': 'S6, S9, S10',
        'senales_de_deteccion': 'Piezas co-marcadas visibles sin descargo ni APR; boletines o espacios publicitarios propios; rol de broker con responsabilidad de cumplimiento; menciones de RESPA',
        'escala_de_intensidad': '0 = sin actividad de co-marketing observable | 1 = co-marketing visible sin senal de estructura | 2 = co-marketing visible con piezas que omiten APR o descargos, o declara dudas | 3 = verbaliza el miedo a la auditoria o evita el canal por ese motivo',
        'evidencia_minima': 'Una pieza co-marcada sin APR es evidencia dura de nivel 2; el nivel 3 exige voz propia',
        'municion_PR_GC': 'PR-98 (prorrateo pro-rata); GC-85, GC-86 (MSA con FMV), GC-89 (TILA-Z), GC-90 (TCPA), GC-94 (AfBA), GC-95, GC-98, GC-103, GC-104',
        'angulo_que_activa': 'A15 "Haz co-marketing sin quedar expuesto"',
        'ruta_de_copy': 'R-E',
        'confianza_tipica': 'media',
    },
    'P-Q22': {
        'familia': 'Pain',
        'enunciado': 'Sus leads se le fugan a portales y plataformas de terceros',
        'nivel_o_tipo': 'Detector · NUEVO v2',
        'categorias_de_senal': 'S1, S4, S9',
        'senales_de_deteccion': 'Dependencia visible de portales para captacion; ausencia de web propia o de entorno de busqueda propio; pauta pagada sin destino propio',
        'escala_de_intensidad': '0 = capta en canal propio con entorno controlado | 1 = sin web ni entorno propio visible | 2 = dependencia declarada o visible de portales de pago | 3 = menciona el costo por lead de portales como problema',
        'evidencia_minima': 'Ausencia de dominio propio sostiene 1; niveles 2 y 3 exigen senal de gasto o voz propia',
        'municion_PR_GC': 'GC-67 (entorno sin publicidad de terceros), GC-73, GC-83, GC-17; PR-92, PR-99',
        'angulo_que_activa': 'A9 vertiente captacion: "deja de alquilar tus leads"',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'baja',
    },
    'G-Q01': {
        'familia': 'Gain',
        'enunciado': 'Rescatar casos hoy perdidos se traduce en ingreso directo e inmediato',
        'nivel_o_tipo': 'Requerida · espejo de P-Q01 · CANON v1.0',
        'categorias_de_senal': 'S3, S8',
        'senales_de_deteccion': 'Se activa por P-Q01 activo; refuerzo si publica casos rescatados o pregunta por programas de nicho',
        'escala_de_intensidad': 'Espejo exacto de P-Q01: intensidad heredada, nunca superior',
        'evidencia_minima': 'La de P-Q01 (un gain espejo no genera evidencia propia)',
        'municion_PR_GC': 'Portafolio de nicho completo',
        'angulo_que_activa': 'A1',
        'ruta_de_copy': 'R-A',
        'confianza_tipica': 'media',
    },
    'G-Q02': {
        'familia': 'Gain',
        'enunciado': 'Cerrar mas rapido significa mas rotacion y mas referidos',
        'nivel_o_tipo': 'Deseada · espejo de P-Q02 y P-Q03 · CANON v1.0',
        'categorias_de_senal': 'S2, S6',
        'senales_de_deteccion': 'P-Q02 o P-Q03 activos; refuerzo si menciona plazos como argumento de venta',
        'escala_de_intensidad': 'Espejo: max(P-Q02, P-Q03), nunca superior',
        'evidencia_minima': 'La de P-Q02 y P-Q03',
        'municion_PR_GC': 'PR-12, PR-14, PR-16; GC-1, GC-30',
        'angulo_que_activa': 'A2',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'G-Q03': {
        'familia': 'Gain',
        'enunciado': 'Monetizar su influencia y su audiencia por una via legal',
        'nivel_o_tipo': 'Deseada · CANON v1.0',
        'categorias_de_senal': 'S1, S9',
        'senales_de_deteccion': 'J-Q04>=2; refuerzo si tiene activos publicitarios propios (boletin, vitrina, canal medible)',
        'escala_de_intensidad': '0 = sin audiencia | 1 = audiencia sin activo monetizable | 2 = audiencia con activo publicitario identificable | 3 = ya monetiza o busca activamente como hacerlo',
        'evidencia_minima': 'Requiere la evidencia de audiencia de J-Q04 mas >=1 activo publicitario observable',
        'municion_PR_GC': 'GC-64 (co-sponsor 50/50 bajo RESPA), GC-86 (MSA con FMV), PR-91 a PR-98',
        'angulo_que_activa': 'A8',
        'ruta_de_copy': 'R-D',
        'confianza_tipica': 'media',
    },
    'G-Q04': {
        'familia': 'Gain',
        'enunciado': 'Posicionarse como la autoridad de su nicho en su mercado',
        'nivel_o_tipo': 'Deseada · CANON v1.0',
        'categorias_de_senal': 'S1, S10, S9',
        'senales_de_deteccion': 'J-Q03 activo mas contenido educativo; ponencias, seminarios o prensa local',
        'escala_de_intensidad': '0 = sin contenido educativo | 1 = contenido ocasional | 2 = contenido educativo recurrente | 3 = reconocimiento externo (ponencias, prensa, comunidad propia)',
        'evidencia_minima': '>=3 piezas educativas fechadas en 180 dias para nivel 2',
        'municion_PR_GC': 'PR-96, PR-97, PR-100; GC-19, GC-77, GC-82',
        'angulo_que_activa': 'A8 secundario; primario solo si P-Q10<=1 (no hay dolor de produccion, hay ambicion de autoridad)',
        'ruta_de_copy': 'R-D',
        'confianza_tipica': 'media',
    },
    'G-Q05': {
        'familia': 'Gain',
        'enunciado': 'Tener un pipeline predecible que elimine el feast-or-famine',
        'nivel_o_tipo': 'Deseada · espejo de J-Q05 · CANON v1.0',
        'categorias_de_senal': 'S2, S4',
        'senales_de_deteccion': 'J-Q05 activo; refuerzo si ausencia de automatizacion visible',
        'escala_de_intensidad': 'Espejo de J-Q05, nunca superior',
        'evidencia_minima': 'La de J-Q05',
        'municion_PR_GC': 'GC-10, GC-12, GC-70, GC-81; PR-99',
        'angulo_que_activa': 'A9',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'G-Q06': {
        'familia': 'Gain',
        'enunciado': 'Abrir segmentos que hoy no puede atender (inversor, extranjero, jumbo)',
        'nivel_o_tipo': 'Inesperada · CANON v1.0',
        'categorias_de_senal': 'S3, S2, S7',
        'senales_de_deteccion': 'P-Q09 o P-Q20 activos; refuerzo si el mercado tiene inventario de inversion o compradores extranjeros',
        'escala_de_intensidad': '0 = sin exposicion | 1 = exposicion posible por mercado | 2 = exposicion real con producto insuficiente | 3 = declara el segmento como objetivo de crecimiento',
        'evidencia_minima': 'Hereda de P-Q09 o P-Q20 el techo de intensidad',
        'municion_PR_GC': 'PR-61 a PR-70; GC-47, GC-49, GC-59, GC-63',
        'angulo_que_activa': 'A7 y A14',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'G-Q07': {
        'familia': 'Gain',
        'enunciado': 'Reducir su costo y su carga de marketing sin perder presencia',
        'nivel_o_tipo': 'Esperada · espejo de P-Q10 · CANON v1.0',
        'categorias_de_senal': 'S1, S9',
        'senales_de_deteccion': 'P-Q10 activo; refuerzo si hay gasto visible en licencias o pauta',
        'escala_de_intensidad': 'Espejo de P-Q10, nunca superior',
        'evidencia_minima': 'La de P-Q10',
        'municion_PR_GC': 'GC-64, GC-65, GC-72, GC-76, GC-78',
        'angulo_que_activa': 'A8',
        'ruta_de_copy': 'R-D',
        'confianza_tipica': 'media',
    },
    'G-Q08': {
        'familia': 'Gain',
        'enunciado': 'Retener su base y generar recompra y referidos de forma automatica',
        'nivel_o_tipo': 'Deseada · espejo de P-Q11 · CANON v1.0',
        'categorias_de_senal': 'S1, S2, S4',
        'senales_de_deteccion': 'P-Q11 activo; refuerzo si trayectoria larga con base amplia',
        'escala_de_intensidad': 'Espejo de P-Q11, nunca superior',
        'evidencia_minima': 'La de P-Q11',
        'municion_PR_GC': 'GC-9, GC-66, GC-81; PR-95',
        'angulo_que_activa': 'A9',
        'ruta_de_copy': 'R-D',
        'confianza_tipica': 'media',
    },
    'G-Q09': {
        'familia': 'Gain',
        'enunciado': 'Operar con tranquilidad regulatoria: que lo que hace resista una revision',
        'nivel_o_tipo': 'Requerida · espejo de P-Q21 · NUEVO v2',
        'categorias_de_senal': 'S6, S9, S10',
        'senales_de_deteccion': 'P-Q21 activo; refuerzo si es broker o tiene responsabilidad de cumplimiento sobre otros agentes',
        'escala_de_intensidad': 'Espejo de P-Q21; puede subir un nivel sobre el pain si el prospecto es broker responsable de terceros (S5/S10)',
        'evidencia_minima': 'La de P-Q21 mas, para el ajuste por rol, evidencia de licencia de broker',
        'municion_PR_GC': 'PR-98; GC-85, GC-86, GC-89, GC-90, GC-94, GC-103, GC-104',
        'angulo_que_activa': 'A15',
        'ruta_de_copy': 'R-E',
        'confianza_tipica': 'media',
    },
    'G-Q10': {
        'familia': 'Gain',
        'enunciado': 'Escalar sobre una estructura existente en vez de construirla',
        'nivel_o_tipo': 'Inesperada · espejo de J-Q07 y J-Q06 · NUEVO v2',
        'categorias_de_senal': 'S5, S4, S10',
        'senales_de_deteccion': 'J-Q07>=2 o J-Q06>=2; refuerzo si menciona costos fijos, nomina o infraestructura',
        'escala_de_intensidad': '0 = sin ambicion estructural | 1 = ambicion declarada sin capacidad | 2 = ambicion mas equipo o SOPs observables | 3 = busca activamente socio de infraestructura o capital',
        'evidencia_minima': 'Hereda el techo de max(J-Q06, J-Q07)',
        'municion_PR_GC': 'GC-16, GC-72, GC-87, GC-88 (Respect Processing), GC-96',
        'angulo_que_activa': 'A17',
        'ruta_de_copy': 'R-D',
        'confianza_tipica': 'baja',
    },
    'PR-Q01': {
        'familia': 'Pain Reliever (paquete ofertable)',
        'enunciado': 'Portafolio de Nicho Latino',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S3, S8',
        'senales_de_deteccion': 'No tiene senales propias: se activa por regla sobre los detectores. Condicion: P-Q01>=2 o P-Q13>=2',
        'escala_de_intensidad': 'Intensidad del paquete = intensidad del pain disparador mas alto; determina la profundidad de la pieza, no su existencia',
        'evidencia_minima': 'La evidencia del pain disparador; sin evidencia-ancla citable el paquete no se oferta',
        'municion_PR_GC': 'Tax ID MAX (640/15%, EEP 580/3.5%), Supreme Dream (3.5% forgivable), Bank Statement, EAD conventional, ITIN; PR-81 a PR-90',
        'angulo_que_activa': 'A1',
        'ruta_de_copy': 'R-A',
        'confianza_tipica': 'media',
    },
    'PR-Q02': {
        'familia': 'Pain Reliever (paquete ofertable)',
        'enunciado': 'Certeza y Velocidad',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S3, S8',
        'senales_de_deteccion': 'No tiene senales propias: se activa por regla sobre los detectores. Condicion: P-Q02>=2 o P-Q03>=2',
        'escala_de_intensidad': 'Intensidad del paquete = intensidad del pain disparador mas alto; determina la profundidad de la pieza, no su existencia',
        'evidencia_minima': 'La evidencia del pain disparador; sin evidencia-ancla citable el paquete no se oferta',
        'municion_PR_GC': 'TBD upfront underwriting (PR-41 a PR-50), suscripcion 24h (PR-12), eClosing (PR-19), procesamiento paralelo (PR-15); GC-1, GC-30',
        'angulo_que_activa': 'A2',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'PR-Q03': {
        'familia': 'Pain Reliever (paquete ofertable)',
        'enunciado': 'Poder de Oferta',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S3, S8',
        'senales_de_deteccion': 'No tiene senales propias: se activa por regla sobre los detectores. Condicion: P-Q04>=2 o P-Q05>=2',
        'escala_de_intensidad': 'Intensidad del paquete = intensidad del pain disparador mas alto; determina la profundidad de la pieza, no su existencia',
        'evidencia_minima': 'La evidencia del pain disparador; sin evidencia-ancla citable el paquete no se oferta',
        'municion_PR_GC': 'Cash-backed (PR-21 a PR-30), appraisal waivers / ROV / gap coverage (PR-51 a PR-60); GC-23, GC-31, GC-37, GC-101',
        'angulo_que_activa': 'A4',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'PR-Q04': {
        'familia': 'Pain Reliever (paquete ofertable)',
        'enunciado': 'Asequibilidad',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S3, S8',
        'senales_de_deteccion': 'No tiene senales propias: se activa por regla sobre los detectores. Condicion: P-Q06>=2 o P-Q07>=2',
        'escala_de_intensidad': 'Intensidad del paquete = intensidad del pain disparador mas alto; determina la profundidad de la pieza, no su existencia',
        'evidencia_minima': 'La evidencia del pain disparador; sin evidencia-ancla citable el paquete no se oferta',
        'municion_PR_GC': 'Buydowns 2-1, 1-0, 3-2-1 y con reembolso; DPA apilable; concesiones del vendedor segun limites IPC (PR-71 a PR-80); Supreme Dream',
        'angulo_que_activa': 'A5',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'PR-Q05': {
        'familia': 'Pain Reliever (paquete ofertable)',
        'enunciado': 'Transicion',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S3, S8',
        'senales_de_deteccion': 'No tiene senales propias: se activa por regla sobre los detectores. Condicion: P-Q08>=2',
        'escala_de_intensidad': 'Intensidad del paquete = intensidad del pain disparador mas alto; determina la profundidad de la pieza, no su existencia',
        'evidencia_minima': 'La evidencia del pain disparador; sin evidencia-ancla citable el paquete no se oferta',
        'municion_PR_GC': 'Bridge, buy-before-sell, segunda carga, colateral cruzado (PR-31 a PR-40); GC-25',
        'angulo_que_activa': 'A6',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'PR-Q06': {
        'familia': 'Pain Reliever (paquete ofertable)',
        'enunciado': 'Inversionista',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S3, S8',
        'senales_de_deteccion': 'No tiene senales propias: se activa por regla sobre los detectores. Condicion: P-Q09>=2',
        'escala_de_intensidad': 'Intensidad del paquete = intensidad del pain disparador mas alto; determina la profundidad de la pieza, no su existencia',
        'evidencia_minima': 'La evidencia del pain disparador; sin evidencia-ancla citable el paquete no se oferta',
        'municion_PR_GC': 'DSCR, titulacion en LLC, interest-only, foreign national, Seccion 1031, Schedule 1007 (PR-61 a PR-70); GC-36, GC-49, GC-54, GC-59',
        'angulo_que_activa': 'A7',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'PR-Q07': {
        'familia': 'Pain Reliever (paquete ofertable)',
        'enunciado': 'Maquina de Marketing',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S3, S8',
        'senales_de_deteccion': 'No tiene senales propias: se activa por regla sobre los detectores. Condicion: P-Q10>=2 o P-Q11>=2 o P-Q22>=2',
        'escala_de_intensidad': 'Intensidad del paquete = intensidad del pain disparador mas alto; determina la profundidad de la pieza, no su existencia',
        'evidencia_minima': 'La evidencia del pain disparador; sin evidencia-ancla citable el paquete no se oferta',
        'municion_PR_GC': 'Co-marketing RESPA-legal 50/50, biblioteca de contenido, seminarios, retencion (PR-91 a PR-100; GC-64 a GC-84)',
        'angulo_que_activa': 'A8 o A9 segun cual pain dispare',
        'ruta_de_copy': 'R-D',
        'confianza_tipica': 'media',
    },
    'PR-Q08': {
        'familia': 'Pain Reliever (paquete ofertable)',
        'enunciado': 'Servicio en Espanol',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S3, S8',
        'senales_de_deteccion': 'No tiene senales propias: se activa por regla sobre los detectores. Condicion: P-Q14>=2',
        'escala_de_intensidad': 'Intensidad del paquete = intensidad del pain disparador mas alto; determina la profundidad de la pieza, no su existencia',
        'evidencia_minima': 'La evidencia del pain disparador; sin evidencia-ancla citable el paquete no se oferta',
        'municion_PR_GC': 'LO bilingue de la casa; materiales y proceso en espanol; PR-100; GC-14',
        'angulo_que_activa': 'A18',
        'ruta_de_copy': 'R-D',
        'confianza_tipica': 'alta',
    },
    'PR-Q09': {
        'familia': 'Pain Reliever (paquete ofertable)',
        'enunciado': 'Portafolio Veterano',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S3, S8',
        'senales_de_deteccion': 'No tiene senales propias: se activa por regla sobre los detectores. Condicion: P-Q17>=2',
        'escala_de_intensidad': 'Intensidad del paquete = intensidad del pain disparador mas alto; determina la profundidad de la pieza, no su existencia',
        'evidencia_minima': 'La evidencia del pain disparador; sin evidencia-ancla citable el paquete no se oferta',
        'municion_PR_GC': 'PR-83 (DTI VA superior al 60% con evaluacion automatizada favorable), PR-84 (ingreso residual), PR-85 (100% sin PMI), PR-82',
        'angulo_que_activa': 'A11',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'PR-Q10': {
        'familia': 'Pain Reliever (paquete ofertable)',
        'enunciado': 'Rescate de Inmueble',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S3, S8',
        'senales_de_deteccion': 'No tiene senales propias: se activa por regla sobre los detectores. Condicion: P-Q18>=2',
        'escala_de_intensidad': 'Intensidad del paquete = intensidad del pain disparador mas alto; determina la profundidad de la pieza, no su existencia',
        'evidencia_minima': 'La evidencia del pain disparador; sin evidencia-ancla citable el paquete no se oferta',
        'municion_PR_GC': 'PR-87 (FHA 203k / Fannie Mae HomeStyle); GC-32, GC-33 (non-warrantable condos), GC-57',
        'angulo_que_activa': 'A12',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'baja',
    },
    'PR-Q11': {
        'familia': 'Pain Reliever (paquete ofertable)',
        'enunciado': 'Reingreso de Credito',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S3, S8',
        'senales_de_deteccion': 'No tiene senales propias: se activa por regla sobre los detectores. Condicion: P-Q19>=2',
        'escala_de_intensidad': 'Intensidad del paquete = intensidad del pain disparador mas alto; determina la profundidad de la pieza, no su existencia',
        'evidencia_minima': 'La evidencia del pain disparador; sin evidencia-ancla citable el paquete no se oferta',
        'municion_PR_GC': 'PR-89 (plazos federales minimos, Capitulo 7 con espera minima de 2 anos); GC-34, GC-55 (Portfolio Select: 1 ano), GC-60',
        'angulo_que_activa': 'A13',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'baja',
    },
    'PR-Q12': {
        'familia': 'Pain Reliever (paquete ofertable)',
        'enunciado': 'Escudo de Cumplimiento',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S3, S8',
        'senales_de_deteccion': 'No tiene senales propias: se activa por regla sobre los detectores. Condicion: P-Q21>=2 o (J-Q04>=2 y P-Q21>=1)',
        'escala_de_intensidad': 'Intensidad del paquete = intensidad del pain disparador mas alto; determina la profundidad de la pieza, no su existencia',
        'evidencia_minima': 'La evidencia del pain disparador; sin evidencia-ancla citable el paquete no se oferta',
        'municion_PR_GC': 'PR-98 (prorrateo pro-rata auditable); GC-85, GC-86 (MSA con estudio de FMV), GC-89 (TILA-Z, APR obligatoria), GC-90 (TCPA), GC-94 (AfBA Disclosure de la CFPB), GC-103, GC-104',
        'angulo_que_activa': 'A15',
        'ruta_de_copy': 'R-E',
        'confianza_tipica': 'media',
    },
    'PR-Q13': {
        'familia': 'Pain Reliever (paquete ofertable)',
        'enunciado': 'Visibilidad del Expediente',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S3, S8',
        'senales_de_deteccion': 'No tiene senales propias: se activa por regla sobre los detectores. Condicion: P-Q15>=2 o P-Q16>=2',
        'escala_de_intensidad': 'Intensidad del paquete = intensidad del pain disparador mas alto; determina la profundidad de la pieza, no su existencia',
        'evidencia_minima': 'La evidencia del pain disparador; sin evidencia-ancla citable el paquete no se oferta',
        'municion_PR_GC': 'PR-1 (VOIE), PR-2 (sincronizacion LOS-CRM), PR-3, PR-4, PR-8, PR-10, PR-20; GC-2, GC-5, GC-79, GC-100',
        'angulo_que_activa': 'A3',
        'ruta_de_copy': 'R-A',
        'confianza_tipica': 'media',
    },
    'PR-Q14': {
        'familia': 'Pain Reliever (paquete ofertable)',
        'enunciado': 'Documentacion Alternativa de Ingreso Alto',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S3, S8',
        'senales_de_deteccion': 'No tiene senales propias: se activa por regla sobre los detectores. Condicion: P-Q20>=2',
        'escala_de_intensidad': 'Intensidad del paquete = intensidad del pain disparador mas alto; determina la profundidad de la pieza, no su existencia',
        'evidencia_minima': 'La evidencia del pain disparador; sin evidencia-ancla citable el paquete no se oferta',
        'municion_PR_GC': 'PR-81 (bank statement 12/24 meses); GC-43, GC-44 (1099), GC-45 (P&L con CPA), GC-46 (asset depletion), GC-51, GC-53, GC-56',
        'angulo_que_activa': 'A14',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'GC-Q01': {
        'familia': 'Gain Creator (paquete ofertable)',
        'enunciado': 'Crecimiento de audiencia co-financiado',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S1, S9, S5',
        'senales_de_deteccion': 'Sin senales propias. Condicion: G-Q03>=2',
        'escala_de_intensidad': 'Intensidad heredada del gain disparador; gobierna el tono aspiracional de la pieza',
        'evidencia_minima': 'La evidencia del gain disparador',
        'municion_PR_GC': 'GC-64, GC-65, GC-68, GC-76, GC-78',
        'angulo_que_activa': 'A8',
        'ruta_de_copy': 'R-D',
        'confianza_tipica': 'media',
    },
    'GC-Q02': {
        'familia': 'Gain Creator (paquete ofertable)',
        'enunciado': 'Autoridad instantanea con contenido y datos locales',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S1, S9, S5',
        'senales_de_deteccion': 'Sin senales propias. Condicion: G-Q04>=2',
        'escala_de_intensidad': 'Intensidad heredada del gain disparador; gobierna el tono aspiracional de la pieza',
        'evidencia_minima': 'La evidencia del gain disparador',
        'municion_PR_GC': 'GC-19, GC-77; PR-96, PR-97, PR-100',
        'angulo_que_activa': 'A8 secundario',
        'ruta_de_copy': 'R-D',
        'confianza_tipica': 'media',
    },
    'GC-Q03': {
        'familia': 'Gain Creator (paquete ofertable)',
        'enunciado': 'Pipeline perpetuo con nurture y senales predictivas',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S1, S9, S5',
        'senales_de_deteccion': 'Sin senales propias. Condicion: G-Q05>=2',
        'escala_de_intensidad': 'Intensidad heredada del gain disparador; gobierna el tono aspiracional de la pieza',
        'evidencia_minima': 'La evidencia del gain disparador',
        'municion_PR_GC': 'GC-9, GC-10, GC-70, GC-81; PR-99',
        'angulo_que_activa': 'A9',
        'ruta_de_copy': 'R-D',
        'confianza_tipica': 'media',
    },
    'GC-Q04': {
        'familia': 'Gain Creator (paquete ofertable)',
        'enunciado': 'Expansion de segmentos',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S1, S9, S5',
        'senales_de_deteccion': 'Sin senales propias. Condicion: G-Q06>=2',
        'escala_de_intensidad': 'Intensidad heredada del gain disparador; gobierna el tono aspiracional de la pieza',
        'evidencia_minima': 'La evidencia del gain disparador',
        'municion_PR_GC': 'GC-43 a GC-63 (Non-QM completo)',
        'angulo_que_activa': 'A7 y A14',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
    'GC-Q05': {
        'familia': 'Gain Creator (paquete ofertable)',
        'enunciado': 'Estructura de plataforma',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S1, S9, S5',
        'senales_de_deteccion': 'Sin senales propias. Condicion: G-Q10>=2 o J-Q07>=2',
        'escala_de_intensidad': 'Intensidad heredada del gain disparador; gobierna el tono aspiracional de la pieza',
        'evidencia_minima': 'La evidencia del gain disparador',
        'municion_PR_GC': 'GC-16, GC-72, GC-87 (Mortgage Joint Ventures), GC-88 (Respect Processing), GC-96',
        'angulo_que_activa': 'A17',
        'ruta_de_copy': 'R-D',
        'confianza_tipica': 'baja',
    },
    'GC-Q06': {
        'familia': 'Gain Creator (paquete ofertable)',
        'enunciado': 'Argumento con datos para defender honorarios',
        'nivel_o_tipo': 'Derivado · no se observa, se activa',
        'categorias_de_senal': 'S1, S9, S5',
        'senales_de_deteccion': 'Sin senales propias. Condicion: J-Q08>=2',
        'escala_de_intensidad': 'Intensidad heredada del gain disparador; gobierna el tono aspiracional de la pieza',
        'evidencia_minima': 'La evidencia del gain disparador',
        'municion_PR_GC': 'GC-19 (Real Estate Report Card), GC-24 (Bid Over Asking Price), GC-29 (Cost of Waiting), GC-42 (LTV Analyzer), GC-75 (Buy vs Rent)',
        'angulo_que_activa': 'A16',
        'ruta_de_copy': 'R-B',
        'confianza_tipica': 'media',
    },
}


def ficha(qualifier: str) -> dict:
    """La ficha de un qualifier, o un dict vacio con su razon.

    No levanta: un qualifier sin ficha es un dato -- significa que el banco no
    lo cubre-- y quien llama tiene que poder decirlo en pantalla en vez de
    romperse.
    """
    return CATALOGO.get(qualifier, {})


def enunciado(qualifier: str) -> str | None:
    """Que se supone que le pasa. `P-Q14` solo no le dice nada a nadie."""
    return ficha(qualifier).get("enunciado")
